package org.velvia.filo

/**
 * Must be implemented for proper building of columns from rows
 */
trait RowIngestSupport[R] {
  def getString(row: R, columnNo: Int): Option[String]
  def getInt(row: R, columnNo: Int): Option[Int]
  def getLong(row: R, columnNo: Int): Option[Long]
  def getDouble(row: R, columnNo: Int): Option[Double]
}

/**
 * Just an example of extracting from a Tuple or Case Class where every element is an Option[T].
 * This happens to be the type generated by a CSV parser.
 */
object TupleRowIngestSupport extends RowIngestSupport[Product] {
  type R = Product
  def getString(row: R, columnNo: Int): Option[String] =
    row.productElement(columnNo).asInstanceOf[Option[String]]
  def getInt(row: R, columnNo: Int): Option[Int] =
    row.productElement(columnNo).asInstanceOf[Option[Int]]
  def getLong(row: R, columnNo: Int): Option[Long] =
    row.productElement(columnNo).asInstanceOf[Option[Long]]
  def getDouble(row: R, columnNo: Int): Option[Double] =
    row.productElement(columnNo).asInstanceOf[Option[Double]]
}
